development:
  adapter: mysql2
  database: chcc_development
  pool: 5
  username: root
  password:

# # test:
# #   adapter: mysql2
# #   database: chcc_test
# #   pool: 5
# #   username: root
# #   password:

production:
  adapter: mysql2
  database: heroku_7282fb213f63b2f
  pool: 5
  username: bdccc90c34835b
  password: 4959444b

staging:
  adapter: mysql2
  database: heroku_fd253a4a0e46e1f
  pool: 5
  username: b291e924fbd322
  password: c3182c6f
