development:
  adapter: mysql2
  database: heroku_7282fb213f63b2f
  pool: 5
  username: bdccc90c34835b
  password: 4959444b
test:
  adapter: mysql2
  database: heroku_7282fb213f63b2f
  pool: 5
  username: bdccc90c34835b
  password: 4959444b

production:
  adapter: mysql2
  database: heroku_7282fb213f63b2f
  pool: 5
  username: bdccc90c34835b
  password: 4959444b
