development:
  adapter: mysql2
  database: chcc_development
  pool: 5
  username: root
  password:

# # test:
# #   adapter: mysql2
# #   database: chcc_test
# #   pool: 5
# #   username: root
# #   password:

production:
  adapter: mysql2
  database: heroku_7282fb213f63b2f
  pool: 5
  username: bdccc90c34835b
  password: 4959444b

staging:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: d7vt3jsbnq1dhn
  pool: 5
  username: dzbcxtuxssikka
  password: l0idV4LIKfu-mwHKCjBTmV0tDh
